#
#       SurvivalGames by iiProCraft - Main configuration
#
# for assistance visit https://github.com/iiProCraft/SurvivalGames/wiki/configuration-config-yml
options:
  # Available server modes:
  #
  # - SHARED:
  # Description: If you want to run the plugin with another mini-games
  #
  # - MULTI_ARENA:
  # Description: If you want to run the plugin with another mini-games
  #
  # - BUNGEE:
  # Description: If you want to separate between lobby and arenas servers

  mode: SHARED
  bungee:
    # Lobby servers:
    # Description: it will pick up a random server from this list
    lobby-servers:
      - SG01L
      - SG02L
    # Server name:
    # Description: This value used to get the server name for bungee
    #              mode to send players to it.
    server-name: 'SG01'
    auto-balance: false
    json:
      directory: '$ROOTDIR/players/'
    sqlite:
      file-path: '$ROOTDIR/data.db'
  vote:
    enabled: true
    max-arenas: 5
    random-vote: true
    vote-algorithm:
      winner-arena-sort: GET_FIRST_ARENA_LIST

# Storage method options:
# 
# Remote databases:
# - MySQL
# - MongoDB
#
# Local database (Do not require any extra configuration):
# - SQLITE
# - JSON

storage-method: SQLITE

storage:

  # The address for the database
  # Database port will be used by default (MongoDB: 27017, MySQL: 3306)
  # Add "port:<your_custom_port>" if differs
  host: 127.0.0.1
  
  # The database where all of survivalgames data will be stored in
  database: survivalgames
  
  # Connection credentials
  username: 'username'
  password: 'password'
  
  # Enable this if you want to increase your database security
  # by encrypting all transactions that are being transmitted between the client and the server
  # however, enabling will slow the database performance
  use-ssl: false
  
  # Maximum size for the MySQL Connection Pool (currently using HikariCP for connection pooling)
  # More information can be found here: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing  
  maximum-pool-size: 10
  
  
messaging:
  redis:
    # To whether enable this messaging feature or not
    # You may want to enable if you want to sync your survival games servers
    enabled: false
    
    # The address for the database
    # Database port which is 6379 will be used by default
    # Add "port:<your_custom_port>" if differs
    host: 127.0.0.1
    
    # The channels which will be used for communication
    channels:
      servers: 'sg_servers'
    
    # Enable authentication, if there are credentials configured
    authentication:
      enabled: false
      username: 'username'
      password: 'password'
