#
#       SurvivalGames by iiProCraft
#
# for assistance visit https://github.com/iiProCraft/SurvivalGames/wiki/configuration/config-yml
options:
  mode: SHARED
  bungee:
    lobby-servers:
      - SG01L
      - SG02L
    server-name: 'SG01'
    auto-scale: false
  storage:
    method: SQLITE # Available: MONGO, MYSQL, SQLITE, JSON
    json:
      directory: '$ROOTDIR/players/'
    sqlite:
      file-path: '$ROOTDIR/data.db'
  vote:
    enabled: true
    max-arenas: 5
    random-vote: true
    vote-algorithm:
      winner-arena-sort: GET_FIRST_ARENA_LIST
connections:
  redis: # It's used to communicate between servers, use it for better performance
    enabled: false
    host: 0.0.0.0:6379
    channels:
      servers: 'sg_servers'
    authentication:
      acl-auth: false
      username: 'redisUser'
      password: 'YeetyPa@asW0rD'
  mysql:
    host: 0.0.0.0:3306
    database: survivalgames
    table-prefix: 'sg_'
    use-ssl: false
    authentication:
      username: 'root'
      password: 'yeetyP@ssw0rd'
  mongodb:
    host: 0.0.0.0:27017
